### PR TITLE
migrated to null safety

### PR DESCRIPTION
**Pull request by pr-1**

### CODE REVIEW

**Comment by pr-1** [comment]
@aolychkin  Please have a look

**Comment by pr-1** [comment]
@aolychkin Please have a look

**Comment by ksydex** [comment]
@pr-1 Thank you for your contribution! I've merged your pull request, at first it didn't work for me because of 
```dart
_controller!.setLooping(looping!);
```
So i changed it to
```dart
_controller!.setLooping(looping == null ? false : true);
```
Also upgraded versions of dependencies because they were not compatible with new plugins that use http ^0.13
Plugin will be updated on pub.dev shortly.

**Comment by pr-1** [comment]
@ksydex When are you planning to release it on pub ??

**Comment by pr-1** [comment]
```dart
   _controller!.setLooping(looping ?? false );
```

This should be a better option for looping.

**Pull request merged**
